name: CI Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 24f2004808@ds.study.iitm.ac.in
        run: echo "Hello, world!"
